# Generated by Django 4.2.4 on 2023-08-21 11:34

from django.apps import registry
from django.db import migrations
from django.db.backends.base import schema


def create_default_tiers(apps: registry.Apps, schema_editor: schema.BaseDatabaseSchemaEditor):
    AccountTier = apps.get_model("images", "AccountTier")
    AccountTier.objects.create(
        name="Basic",
        thumbnail_sizes=[200],
        include_original_file=False,
        can_generate_expiring_links=False,
    )
    AccountTier.objects.create(
        name="Premium",
        thumbnail_sizes=[200, 400],
        include_original_file=True,
        can_generate_expiring_links=False,
    )
    AccountTier.objects.create(
        name="Enterprise",
        thumbnail_sizes=[200, 400],
        include_original_file=True,
        can_generate_expiring_links=True,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_default_tiers, reverse_code=migrations.RunPython.noop),
    ]
